package me.tspace.finance.spend.dao;

import me.tspace.finance.spend.pojo.MoneySpend;

public interface MoneySpendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_spend
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_spend
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    int insert(MoneySpend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_spend
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    int insertSelective(MoneySpend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_spend
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    MoneySpend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_spend
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    int updateByPrimaryKeySelective(MoneySpend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_spend
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    int updateByPrimaryKey(MoneySpend record);
}