package me.tspace.finance.regular.dao;

import me.tspace.finance.regular.pojo.MoneyRegular;

public interface MoneyRegularMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_regular
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_regular
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    int insert(MoneyRegular record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_regular
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    int insertSelective(MoneyRegular record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_regular
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    MoneyRegular selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_regular
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    int updateByPrimaryKeySelective(MoneyRegular record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_regular
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    int updateByPrimaryKey(MoneyRegular record);
}