package me.tspace.finance.category.pojo;

public class MoneyCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_category.id
     *
     * @mbggenerated Thu Sep 12 23:00:05 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_category.category_type
     *
     * @mbggenerated Thu Sep 12 23:00:05 CST 2013
     */
    private String categoryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_category.name
     *
     * @mbggenerated Thu Sep 12 23:00:05 CST 2013
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_category.id
     *
     * @return the value of t_money_category.id
     *
     * @mbggenerated Thu Sep 12 23:00:05 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_category.id
     *
     * @param id the value for t_money_category.id
     *
     * @mbggenerated Thu Sep 12 23:00:05 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_category.category_type
     *
     * @return the value of t_money_category.category_type
     *
     * @mbggenerated Thu Sep 12 23:00:05 CST 2013
     */
    public String getCategoryType() {
        return categoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_category.category_type
     *
     * @param categoryType the value for t_money_category.category_type
     *
     * @mbggenerated Thu Sep 12 23:00:05 CST 2013
     */
    public void setCategoryType(String categoryType) {
        this.categoryType = categoryType == null ? null : categoryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_category.name
     *
     * @return the value of t_money_category.name
     *
     * @mbggenerated Thu Sep 12 23:00:05 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_category.name
     *
     * @param name the value for t_money_category.name
     *
     * @mbggenerated Thu Sep 12 23:00:05 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}