package me.tspace.finance.income.pojo;

import java.util.Date;

public class MoneyIncome {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_income.id
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_income.income_type
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    private Integer incomeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_income.amount
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    private Float amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_income.create_date
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_income.remark
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_income.id
     *
     * @return the value of t_money_income.id
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_income.id
     *
     * @param id the value for t_money_income.id
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_income.income_type
     *
     * @return the value of t_money_income.income_type
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    public Integer getIncomeType() {
        return incomeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_income.income_type
     *
     * @param incomeType the value for t_money_income.income_type
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    public void setIncomeType(Integer incomeType) {
        this.incomeType = incomeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_income.amount
     *
     * @return the value of t_money_income.amount
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_income.amount
     *
     * @param amount the value for t_money_income.amount
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_income.create_date
     *
     * @return the value of t_money_income.create_date
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_income.create_date
     *
     * @param createDate the value for t_money_income.create_date
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_income.remark
     *
     * @return the value of t_money_income.remark
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_income.remark
     *
     * @param remark the value for t_money_income.remark
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}