package me.tspace.pm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LoginExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	public LoginExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andLoginIdIsNull() {
			addCriterion("LOGIN_ID is null");
			return (Criteria) this;
		}

		public Criteria andLoginIdIsNotNull() {
			addCriterion("LOGIN_ID is not null");
			return (Criteria) this;
		}

		public Criteria andLoginIdEqualTo(Integer value) {
			addCriterion("LOGIN_ID =", value, "loginId");
			return (Criteria) this;
		}

		public Criteria andLoginIdNotEqualTo(Integer value) {
			addCriterion("LOGIN_ID <>", value, "loginId");
			return (Criteria) this;
		}

		public Criteria andLoginIdGreaterThan(Integer value) {
			addCriterion("LOGIN_ID >", value, "loginId");
			return (Criteria) this;
		}

		public Criteria andLoginIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("LOGIN_ID >=", value, "loginId");
			return (Criteria) this;
		}

		public Criteria andLoginIdLessThan(Integer value) {
			addCriterion("LOGIN_ID <", value, "loginId");
			return (Criteria) this;
		}

		public Criteria andLoginIdLessThanOrEqualTo(Integer value) {
			addCriterion("LOGIN_ID <=", value, "loginId");
			return (Criteria) this;
		}

		public Criteria andLoginIdIn(List<Integer> values) {
			addCriterion("LOGIN_ID in", values, "loginId");
			return (Criteria) this;
		}

		public Criteria andLoginIdNotIn(List<Integer> values) {
			addCriterion("LOGIN_ID not in", values, "loginId");
			return (Criteria) this;
		}

		public Criteria andLoginIdBetween(Integer value1, Integer value2) {
			addCriterion("LOGIN_ID between", value1, value2, "loginId");
			return (Criteria) this;
		}

		public Criteria andLoginIdNotBetween(Integer value1, Integer value2) {
			addCriterion("LOGIN_ID not between", value1, value2, "loginId");
			return (Criteria) this;
		}

		public Criteria andLoginNameIsNull() {
			addCriterion("LOGIN_NAME is null");
			return (Criteria) this;
		}

		public Criteria andLoginNameIsNotNull() {
			addCriterion("LOGIN_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andLoginNameEqualTo(String value) {
			addCriterion("LOGIN_NAME =", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotEqualTo(String value) {
			addCriterion("LOGIN_NAME <>", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameGreaterThan(String value) {
			addCriterion("LOGIN_NAME >", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
			addCriterion("LOGIN_NAME >=", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameLessThan(String value) {
			addCriterion("LOGIN_NAME <", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameLessThanOrEqualTo(String value) {
			addCriterion("LOGIN_NAME <=", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameLike(String value) {
			addCriterion("LOGIN_NAME like", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotLike(String value) {
			addCriterion("LOGIN_NAME not like", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameIn(List<String> values) {
			addCriterion("LOGIN_NAME in", values, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotIn(List<String> values) {
			addCriterion("LOGIN_NAME not in", values, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameBetween(String value1, String value2) {
			addCriterion("LOGIN_NAME between", value1, value2, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotBetween(String value1, String value2) {
			addCriterion("LOGIN_NAME not between", value1, value2, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginEmailIsNull() {
			addCriterion("LOGIN_EMAIL is null");
			return (Criteria) this;
		}

		public Criteria andLoginEmailIsNotNull() {
			addCriterion("LOGIN_EMAIL is not null");
			return (Criteria) this;
		}

		public Criteria andLoginEmailEqualTo(String value) {
			addCriterion("LOGIN_EMAIL =", value, "loginEmail");
			return (Criteria) this;
		}

		public Criteria andLoginEmailNotEqualTo(String value) {
			addCriterion("LOGIN_EMAIL <>", value, "loginEmail");
			return (Criteria) this;
		}

		public Criteria andLoginEmailGreaterThan(String value) {
			addCriterion("LOGIN_EMAIL >", value, "loginEmail");
			return (Criteria) this;
		}

		public Criteria andLoginEmailGreaterThanOrEqualTo(String value) {
			addCriterion("LOGIN_EMAIL >=", value, "loginEmail");
			return (Criteria) this;
		}

		public Criteria andLoginEmailLessThan(String value) {
			addCriterion("LOGIN_EMAIL <", value, "loginEmail");
			return (Criteria) this;
		}

		public Criteria andLoginEmailLessThanOrEqualTo(String value) {
			addCriterion("LOGIN_EMAIL <=", value, "loginEmail");
			return (Criteria) this;
		}

		public Criteria andLoginEmailLike(String value) {
			addCriterion("LOGIN_EMAIL like", value, "loginEmail");
			return (Criteria) this;
		}

		public Criteria andLoginEmailNotLike(String value) {
			addCriterion("LOGIN_EMAIL not like", value, "loginEmail");
			return (Criteria) this;
		}

		public Criteria andLoginEmailIn(List<String> values) {
			addCriterion("LOGIN_EMAIL in", values, "loginEmail");
			return (Criteria) this;
		}

		public Criteria andLoginEmailNotIn(List<String> values) {
			addCriterion("LOGIN_EMAIL not in", values, "loginEmail");
			return (Criteria) this;
		}

		public Criteria andLoginEmailBetween(String value1, String value2) {
			addCriterion("LOGIN_EMAIL between", value1, value2, "loginEmail");
			return (Criteria) this;
		}

		public Criteria andLoginEmailNotBetween(String value1, String value2) {
			addCriterion("LOGIN_EMAIL not between", value1, value2,
					"loginEmail");
			return (Criteria) this;
		}

		public Criteria andLoginPwdIsNull() {
			addCriterion("LOGIN_PWD is null");
			return (Criteria) this;
		}

		public Criteria andLoginPwdIsNotNull() {
			addCriterion("LOGIN_PWD is not null");
			return (Criteria) this;
		}

		public Criteria andLoginPwdEqualTo(String value) {
			addCriterion("LOGIN_PWD =", value, "loginPwd");
			return (Criteria) this;
		}

		public Criteria andLoginPwdNotEqualTo(String value) {
			addCriterion("LOGIN_PWD <>", value, "loginPwd");
			return (Criteria) this;
		}

		public Criteria andLoginPwdGreaterThan(String value) {
			addCriterion("LOGIN_PWD >", value, "loginPwd");
			return (Criteria) this;
		}

		public Criteria andLoginPwdGreaterThanOrEqualTo(String value) {
			addCriterion("LOGIN_PWD >=", value, "loginPwd");
			return (Criteria) this;
		}

		public Criteria andLoginPwdLessThan(String value) {
			addCriterion("LOGIN_PWD <", value, "loginPwd");
			return (Criteria) this;
		}

		public Criteria andLoginPwdLessThanOrEqualTo(String value) {
			addCriterion("LOGIN_PWD <=", value, "loginPwd");
			return (Criteria) this;
		}

		public Criteria andLoginPwdLike(String value) {
			addCriterion("LOGIN_PWD like", value, "loginPwd");
			return (Criteria) this;
		}

		public Criteria andLoginPwdNotLike(String value) {
			addCriterion("LOGIN_PWD not like", value, "loginPwd");
			return (Criteria) this;
		}

		public Criteria andLoginPwdIn(List<String> values) {
			addCriterion("LOGIN_PWD in", values, "loginPwd");
			return (Criteria) this;
		}

		public Criteria andLoginPwdNotIn(List<String> values) {
			addCriterion("LOGIN_PWD not in", values, "loginPwd");
			return (Criteria) this;
		}

		public Criteria andLoginPwdBetween(String value1, String value2) {
			addCriterion("LOGIN_PWD between", value1, value2, "loginPwd");
			return (Criteria) this;
		}

		public Criteria andLoginPwdNotBetween(String value1, String value2) {
			addCriterion("LOGIN_PWD not between", value1, value2, "loginPwd");
			return (Criteria) this;
		}

		public Criteria andLoginLevelIsNull() {
			addCriterion("LOGIN_LEVEL is null");
			return (Criteria) this;
		}

		public Criteria andLoginLevelIsNotNull() {
			addCriterion("LOGIN_LEVEL is not null");
			return (Criteria) this;
		}

		public Criteria andLoginLevelEqualTo(Integer value) {
			addCriterion("LOGIN_LEVEL =", value, "loginLevel");
			return (Criteria) this;
		}

		public Criteria andLoginLevelNotEqualTo(Integer value) {
			addCriterion("LOGIN_LEVEL <>", value, "loginLevel");
			return (Criteria) this;
		}

		public Criteria andLoginLevelGreaterThan(Integer value) {
			addCriterion("LOGIN_LEVEL >", value, "loginLevel");
			return (Criteria) this;
		}

		public Criteria andLoginLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("LOGIN_LEVEL >=", value, "loginLevel");
			return (Criteria) this;
		}

		public Criteria andLoginLevelLessThan(Integer value) {
			addCriterion("LOGIN_LEVEL <", value, "loginLevel");
			return (Criteria) this;
		}

		public Criteria andLoginLevelLessThanOrEqualTo(Integer value) {
			addCriterion("LOGIN_LEVEL <=", value, "loginLevel");
			return (Criteria) this;
		}

		public Criteria andLoginLevelIn(List<Integer> values) {
			addCriterion("LOGIN_LEVEL in", values, "loginLevel");
			return (Criteria) this;
		}

		public Criteria andLoginLevelNotIn(List<Integer> values) {
			addCriterion("LOGIN_LEVEL not in", values, "loginLevel");
			return (Criteria) this;
		}

		public Criteria andLoginLevelBetween(Integer value1, Integer value2) {
			addCriterion("LOGIN_LEVEL between", value1, value2, "loginLevel");
			return (Criteria) this;
		}

		public Criteria andLoginLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("LOGIN_LEVEL not between", value1, value2,
					"loginLevel");
			return (Criteria) this;
		}

		public Criteria andLoginIpIsNull() {
			addCriterion("LOGIN_IP is null");
			return (Criteria) this;
		}

		public Criteria andLoginIpIsNotNull() {
			addCriterion("LOGIN_IP is not null");
			return (Criteria) this;
		}

		public Criteria andLoginIpEqualTo(String value) {
			addCriterion("LOGIN_IP =", value, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpNotEqualTo(String value) {
			addCriterion("LOGIN_IP <>", value, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpGreaterThan(String value) {
			addCriterion("LOGIN_IP >", value, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpGreaterThanOrEqualTo(String value) {
			addCriterion("LOGIN_IP >=", value, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpLessThan(String value) {
			addCriterion("LOGIN_IP <", value, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpLessThanOrEqualTo(String value) {
			addCriterion("LOGIN_IP <=", value, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpLike(String value) {
			addCriterion("LOGIN_IP like", value, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpNotLike(String value) {
			addCriterion("LOGIN_IP not like", value, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpIn(List<String> values) {
			addCriterion("LOGIN_IP in", values, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpNotIn(List<String> values) {
			addCriterion("LOGIN_IP not in", values, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpBetween(String value1, String value2) {
			addCriterion("LOGIN_IP between", value1, value2, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpNotBetween(String value1, String value2) {
			addCriterion("LOGIN_IP not between", value1, value2, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginRegdateIsNull() {
			addCriterion("LOGIN_REGDATE is null");
			return (Criteria) this;
		}

		public Criteria andLoginRegdateIsNotNull() {
			addCriterion("LOGIN_REGDATE is not null");
			return (Criteria) this;
		}

		public Criteria andLoginRegdateEqualTo(Date value) {
			addCriterion("LOGIN_REGDATE =", value, "loginRegdate");
			return (Criteria) this;
		}

		public Criteria andLoginRegdateNotEqualTo(Date value) {
			addCriterion("LOGIN_REGDATE <>", value, "loginRegdate");
			return (Criteria) this;
		}

		public Criteria andLoginRegdateGreaterThan(Date value) {
			addCriterion("LOGIN_REGDATE >", value, "loginRegdate");
			return (Criteria) this;
		}

		public Criteria andLoginRegdateGreaterThanOrEqualTo(Date value) {
			addCriterion("LOGIN_REGDATE >=", value, "loginRegdate");
			return (Criteria) this;
		}

		public Criteria andLoginRegdateLessThan(Date value) {
			addCriterion("LOGIN_REGDATE <", value, "loginRegdate");
			return (Criteria) this;
		}

		public Criteria andLoginRegdateLessThanOrEqualTo(Date value) {
			addCriterion("LOGIN_REGDATE <=", value, "loginRegdate");
			return (Criteria) this;
		}

		public Criteria andLoginRegdateIn(List<Date> values) {
			addCriterion("LOGIN_REGDATE in", values, "loginRegdate");
			return (Criteria) this;
		}

		public Criteria andLoginRegdateNotIn(List<Date> values) {
			addCriterion("LOGIN_REGDATE not in", values, "loginRegdate");
			return (Criteria) this;
		}

		public Criteria andLoginRegdateBetween(Date value1, Date value2) {
			addCriterion("LOGIN_REGDATE between", value1, value2,
					"loginRegdate");
			return (Criteria) this;
		}

		public Criteria andLoginRegdateNotBetween(Date value1, Date value2) {
			addCriterion("LOGIN_REGDATE not between", value1, value2,
					"loginRegdate");
			return (Criteria) this;
		}

		public Criteria andLoginLastdateIsNull() {
			addCriterion("LOGIN_LASTDATE is null");
			return (Criteria) this;
		}

		public Criteria andLoginLastdateIsNotNull() {
			addCriterion("LOGIN_LASTDATE is not null");
			return (Criteria) this;
		}

		public Criteria andLoginLastdateEqualTo(Date value) {
			addCriterion("LOGIN_LASTDATE =", value, "loginLastdate");
			return (Criteria) this;
		}

		public Criteria andLoginLastdateNotEqualTo(Date value) {
			addCriterion("LOGIN_LASTDATE <>", value, "loginLastdate");
			return (Criteria) this;
		}

		public Criteria andLoginLastdateGreaterThan(Date value) {
			addCriterion("LOGIN_LASTDATE >", value, "loginLastdate");
			return (Criteria) this;
		}

		public Criteria andLoginLastdateGreaterThanOrEqualTo(Date value) {
			addCriterion("LOGIN_LASTDATE >=", value, "loginLastdate");
			return (Criteria) this;
		}

		public Criteria andLoginLastdateLessThan(Date value) {
			addCriterion("LOGIN_LASTDATE <", value, "loginLastdate");
			return (Criteria) this;
		}

		public Criteria andLoginLastdateLessThanOrEqualTo(Date value) {
			addCriterion("LOGIN_LASTDATE <=", value, "loginLastdate");
			return (Criteria) this;
		}

		public Criteria andLoginLastdateIn(List<Date> values) {
			addCriterion("LOGIN_LASTDATE in", values, "loginLastdate");
			return (Criteria) this;
		}

		public Criteria andLoginLastdateNotIn(List<Date> values) {
			addCriterion("LOGIN_LASTDATE not in", values, "loginLastdate");
			return (Criteria) this;
		}

		public Criteria andLoginLastdateBetween(Date value1, Date value2) {
			addCriterion("LOGIN_LASTDATE between", value1, value2,
					"loginLastdate");
			return (Criteria) this;
		}

		public Criteria andLoginLastdateNotBetween(Date value1, Date value2) {
			addCriterion("LOGIN_LASTDATE not between", value1, value2,
					"loginLastdate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_login
     *
     * @mbggenerated do_not_delete_during_merge Sun May 26 14:00:34 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}