package me.tspace.pm.model;

public class Pathway {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selleck_interest_pathway_wan.id
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selleck_interest_pathway_wan.pathwayname
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    private String pathwayname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selleck_interest_pathway_wan.pathwayinterest
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    private Double pathwayinterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selleck_interest_pathway_wan.pathwayvisits
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    private Integer pathwayvisits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selleck_interest_pathway_wan.pathwaytime
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    private Integer pathwaytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selleck_interest_pathway_wan.basicid
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    private Integer basicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selleck_interest_pathway_wan.sortId
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    private Integer sortid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selleck_interest_pathway_wan.bigCategoryId
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    private Integer bigcategoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selleck_interest_pathway_wan.email
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selleck_interest_pathway_wan.id
     *
     * @return the value of selleck_interest_pathway_wan.id
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selleck_interest_pathway_wan.id
     *
     * @param id the value for selleck_interest_pathway_wan.id
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selleck_interest_pathway_wan.pathwayname
     *
     * @return the value of selleck_interest_pathway_wan.pathwayname
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    public String getPathwayname() {
        return pathwayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selleck_interest_pathway_wan.pathwayname
     *
     * @param pathwayname the value for selleck_interest_pathway_wan.pathwayname
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    public void setPathwayname(String pathwayname) {
        this.pathwayname = pathwayname == null ? null : pathwayname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selleck_interest_pathway_wan.pathwayinterest
     *
     * @return the value of selleck_interest_pathway_wan.pathwayinterest
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    public Double getPathwayinterest() {
        return pathwayinterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selleck_interest_pathway_wan.pathwayinterest
     *
     * @param pathwayinterest the value for selleck_interest_pathway_wan.pathwayinterest
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    public void setPathwayinterest(Double pathwayinterest) {
        this.pathwayinterest = pathwayinterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selleck_interest_pathway_wan.pathwayvisits
     *
     * @return the value of selleck_interest_pathway_wan.pathwayvisits
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    public Integer getPathwayvisits() {
        return pathwayvisits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selleck_interest_pathway_wan.pathwayvisits
     *
     * @param pathwayvisits the value for selleck_interest_pathway_wan.pathwayvisits
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    public void setPathwayvisits(Integer pathwayvisits) {
        this.pathwayvisits = pathwayvisits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selleck_interest_pathway_wan.pathwaytime
     *
     * @return the value of selleck_interest_pathway_wan.pathwaytime
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    public Integer getPathwaytime() {
        return pathwaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selleck_interest_pathway_wan.pathwaytime
     *
     * @param pathwaytime the value for selleck_interest_pathway_wan.pathwaytime
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    public void setPathwaytime(Integer pathwaytime) {
        this.pathwaytime = pathwaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selleck_interest_pathway_wan.basicid
     *
     * @return the value of selleck_interest_pathway_wan.basicid
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    public Integer getBasicid() {
        return basicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selleck_interest_pathway_wan.basicid
     *
     * @param basicid the value for selleck_interest_pathway_wan.basicid
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    public void setBasicid(Integer basicid) {
        this.basicid = basicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selleck_interest_pathway_wan.sortId
     *
     * @return the value of selleck_interest_pathway_wan.sortId
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    public Integer getSortid() {
        return sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selleck_interest_pathway_wan.sortId
     *
     * @param sortid the value for selleck_interest_pathway_wan.sortId
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    public void setSortid(Integer sortid) {
        this.sortid = sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selleck_interest_pathway_wan.bigCategoryId
     *
     * @return the value of selleck_interest_pathway_wan.bigCategoryId
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    public Integer getBigcategoryid() {
        return bigcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selleck_interest_pathway_wan.bigCategoryId
     *
     * @param bigcategoryid the value for selleck_interest_pathway_wan.bigCategoryId
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    public void setBigcategoryid(Integer bigcategoryid) {
        this.bigcategoryid = bigcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selleck_interest_pathway_wan.email
     *
     * @return the value of selleck_interest_pathway_wan.email
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selleck_interest_pathway_wan.email
     *
     * @param email the value for selleck_interest_pathway_wan.email
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}