package me.tspace.pm.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.USER_ID
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.USER_LOGIN_ID
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	private Integer userLoginId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.USER_FAMILY_ID
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	private Integer userFamilyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.USER_LEVEL
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	private Integer userLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.USER_NAME
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.USER_EMAIL
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	private String userEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.USER_REGDATE
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	private Date userRegdate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.USER_ID
	 * @return  the value of t_user.USER_ID
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.USER_ID
	 * @param userId  the value for t_user.USER_ID
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.USER_LOGIN_ID
	 * @return  the value of t_user.USER_LOGIN_ID
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	public Integer getUserLoginId() {
		return userLoginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.USER_LOGIN_ID
	 * @param userLoginId  the value for t_user.USER_LOGIN_ID
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	public void setUserLoginId(Integer userLoginId) {
		this.userLoginId = userLoginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.USER_FAMILY_ID
	 * @return  the value of t_user.USER_FAMILY_ID
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	public Integer getUserFamilyId() {
		return userFamilyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.USER_FAMILY_ID
	 * @param userFamilyId  the value for t_user.USER_FAMILY_ID
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	public void setUserFamilyId(Integer userFamilyId) {
		this.userFamilyId = userFamilyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.USER_LEVEL
	 * @return  the value of t_user.USER_LEVEL
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	public Integer getUserLevel() {
		return userLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.USER_LEVEL
	 * @param userLevel  the value for t_user.USER_LEVEL
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	public void setUserLevel(Integer userLevel) {
		this.userLevel = userLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.USER_NAME
	 * @return  the value of t_user.USER_NAME
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.USER_NAME
	 * @param userName  the value for t_user.USER_NAME
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.USER_EMAIL
	 * @return  the value of t_user.USER_EMAIL
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	public String getUserEmail() {
		return userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.USER_EMAIL
	 * @param userEmail  the value for t_user.USER_EMAIL
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail == null ? null : userEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.USER_REGDATE
	 * @return  the value of t_user.USER_REGDATE
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	public Date getUserRegdate() {
		return userRegdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.USER_REGDATE
	 * @param userRegdate  the value for t_user.USER_REGDATE
	 * @mbggenerated  Thu Jun 06 15:59:42 CST 2013
	 */
	public void setUserRegdate(Date userRegdate) {
		this.userRegdate = userRegdate;
	}
}