package me.tspace.pm.dao;

import java.util.List;
import me.tspace.pm.model.Login;
import me.tspace.pm.model.LoginExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface LoginMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	int countByExample(LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	int deleteByExample(LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	int deleteByPrimaryKey(Integer loginId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	int insert(Login record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	int insertSelective(Login record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	List<Login> selectByExample(LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	Login selectByPrimaryKey(Integer loginId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Login record,
			@Param("example") LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	int updateByExample(@Param("record") Login record,
			@Param("example") LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	int updateByPrimaryKeySelective(Login record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Wed Jun 05 23:10:15 CST 2013
	 */
	int updateByPrimaryKey(Login record);
}