package me.tspace.pm.dao;

import java.util.List;
import me.tspace.pm.model.Pathway;
import me.tspace.pm.model.PathwayExample;
import org.apache.ibatis.annotations.Param;

public interface PathwayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selleck_interest_pathway_wan
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    int countByExample(PathwayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selleck_interest_pathway_wan
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    int deleteByExample(PathwayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selleck_interest_pathway_wan
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selleck_interest_pathway_wan
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    int insert(Pathway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selleck_interest_pathway_wan
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    int insertSelective(Pathway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selleck_interest_pathway_wan
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    List<Pathway> selectByExample(PathwayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selleck_interest_pathway_wan
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    Pathway selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selleck_interest_pathway_wan
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    int updateByExampleSelective(@Param("record") Pathway record, @Param("example") PathwayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selleck_interest_pathway_wan
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    int updateByExample(@Param("record") Pathway record, @Param("example") PathwayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selleck_interest_pathway_wan
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    int updateByPrimaryKeySelective(Pathway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selleck_interest_pathway_wan
     *
     * @mbggenerated Fri Jun 07 16:47:12 CST 2013
     */
    int updateByPrimaryKey(Pathway record);
}