package me.tspace.pm.dao;

import java.util.List;
import me.tspace.pm.model.TLogin;
import me.tspace.pm.model.TLoginExample;
import org.apache.ibatis.annotations.Param;

public interface TLoginMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Tue May 21 23:12:25 CST 2013
	 */
	int countByExample(TLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Tue May 21 23:12:25 CST 2013
	 */
	int deleteByExample(TLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Tue May 21 23:12:25 CST 2013
	 */
	int deleteByPrimaryKey(Integer loginId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Tue May 21 23:12:25 CST 2013
	 */
	int insert(TLogin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Tue May 21 23:12:25 CST 2013
	 */
	int insertSelective(TLogin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Tue May 21 23:12:25 CST 2013
	 */
	List<TLogin> selectByExample(TLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Tue May 21 23:12:25 CST 2013
	 */
	TLogin selectByPrimaryKey(Integer loginId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Tue May 21 23:12:25 CST 2013
	 */
	int updateByExampleSelective(@Param("record") TLogin record,
			@Param("example") TLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Tue May 21 23:12:25 CST 2013
	 */
	int updateByExample(@Param("record") TLogin record,
			@Param("example") TLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Tue May 21 23:12:25 CST 2013
	 */
	int updateByPrimaryKeySelective(TLogin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_login
	 * @mbggenerated  Tue May 21 23:12:25 CST 2013
	 */
	int updateByPrimaryKey(TLogin record);
}