package me.tspace.finance.debt.pojo;

import java.util.Date;

public class MoneyDebt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_debt.id
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_debt.debt_type
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    private String debtType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_debt.amount
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    private Float amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_debt.dist_name
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    private String distName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_debt.create_date
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_debt.remark
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_debt.id
     *
     * @return the value of t_money_debt.id
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_debt.id
     *
     * @param id the value for t_money_debt.id
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_debt.debt_type
     *
     * @return the value of t_money_debt.debt_type
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    public String getDebtType() {
        return debtType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_debt.debt_type
     *
     * @param debtType the value for t_money_debt.debt_type
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    public void setDebtType(String debtType) {
        this.debtType = debtType == null ? null : debtType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_debt.amount
     *
     * @return the value of t_money_debt.amount
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_debt.amount
     *
     * @param amount the value for t_money_debt.amount
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_debt.dist_name
     *
     * @return the value of t_money_debt.dist_name
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    public String getDistName() {
        return distName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_debt.dist_name
     *
     * @param distName the value for t_money_debt.dist_name
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    public void setDistName(String distName) {
        this.distName = distName == null ? null : distName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_debt.create_date
     *
     * @return the value of t_money_debt.create_date
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_debt.create_date
     *
     * @param createDate the value for t_money_debt.create_date
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_debt.remark
     *
     * @return the value of t_money_debt.remark
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_debt.remark
     *
     * @param remark the value for t_money_debt.remark
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}