package me.tspace.finance.income.dao;

import me.tspace.finance.income.pojo.MoneyIncome;

public interface MoneyIncomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_income
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_income
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    int insert(MoneyIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_income
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    int insertSelective(MoneyIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_income
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    MoneyIncome selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_income
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    int updateByPrimaryKeySelective(MoneyIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_income
     *
     * @mbggenerated Thu Sep 12 23:03:24 CST 2013
     */
    int updateByPrimaryKey(MoneyIncome record);
}