package me.tspace.finance.spend.pojo;

import java.util.Date;

public class MoneySpend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_spend.id
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_spend.spend_type
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    private Integer spendType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_spend.amount
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    private Float amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_spend.create_date
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_spend.remark
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_spend.id
     *
     * @return the value of t_money_spend.id
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_spend.id
     *
     * @param id the value for t_money_spend.id
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_spend.spend_type
     *
     * @return the value of t_money_spend.spend_type
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    public Integer getSpendType() {
        return spendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_spend.spend_type
     *
     * @param spendType the value for t_money_spend.spend_type
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    public void setSpendType(Integer spendType) {
        this.spendType = spendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_spend.amount
     *
     * @return the value of t_money_spend.amount
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_spend.amount
     *
     * @param amount the value for t_money_spend.amount
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_spend.create_date
     *
     * @return the value of t_money_spend.create_date
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_spend.create_date
     *
     * @param createDate the value for t_money_spend.create_date
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_spend.remark
     *
     * @return the value of t_money_spend.remark
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_spend.remark
     *
     * @param remark the value for t_money_spend.remark
     *
     * @mbggenerated Thu Sep 12 23:04:58 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}