package me.tspace.finance.debt.dao;

import me.tspace.finance.debt.pojo.MoneyDebt;

public interface MoneyDebtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_debt
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_debt
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    int insert(MoneyDebt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_debt
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    int insertSelective(MoneyDebt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_debt
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    MoneyDebt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_debt
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    int updateByPrimaryKeySelective(MoneyDebt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_debt
     *
     * @mbggenerated Thu Sep 12 23:01:08 CST 2013
     */
    int updateByPrimaryKey(MoneyDebt record);
}