package me.tspace.finance.invest.dao;

import me.tspace.finance.invest.pojo.MoneyInvest;

public interface MoneyInvestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_invest
     *
     * @mbggenerated Thu Sep 12 23:04:00 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_invest
     *
     * @mbggenerated Thu Sep 12 23:04:00 CST 2013
     */
    int insert(MoneyInvest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_invest
     *
     * @mbggenerated Thu Sep 12 23:04:00 CST 2013
     */
    int insertSelective(MoneyInvest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_invest
     *
     * @mbggenerated Thu Sep 12 23:04:00 CST 2013
     */
    MoneyInvest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_invest
     *
     * @mbggenerated Thu Sep 12 23:04:00 CST 2013
     */
    int updateByPrimaryKeySelective(MoneyInvest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_invest
     *
     * @mbggenerated Thu Sep 12 23:04:00 CST 2013
     */
    int updateByPrimaryKey(MoneyInvest record);
}