package me.tspace.finance.regular.pojo;

import java.util.Date;

public class MoneyRegular {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_regular.id
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_regular.regular_type
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    private Integer regularType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_regular.amount
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    private Float amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_regular.cycle
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    private String cycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_regular.start_date
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_regular.last_date
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    private Date lastDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_regular.exe_time
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    private Integer exeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_regular.remark
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_regular.id
     *
     * @return the value of t_money_regular.id
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_regular.id
     *
     * @param id the value for t_money_regular.id
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_regular.regular_type
     *
     * @return the value of t_money_regular.regular_type
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    public Integer getRegularType() {
        return regularType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_regular.regular_type
     *
     * @param regularType the value for t_money_regular.regular_type
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    public void setRegularType(Integer regularType) {
        this.regularType = regularType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_regular.amount
     *
     * @return the value of t_money_regular.amount
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_regular.amount
     *
     * @param amount the value for t_money_regular.amount
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_regular.cycle
     *
     * @return the value of t_money_regular.cycle
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    public String getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_regular.cycle
     *
     * @param cycle the value for t_money_regular.cycle
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    public void setCycle(String cycle) {
        this.cycle = cycle == null ? null : cycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_regular.start_date
     *
     * @return the value of t_money_regular.start_date
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_regular.start_date
     *
     * @param startDate the value for t_money_regular.start_date
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_regular.last_date
     *
     * @return the value of t_money_regular.last_date
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    public Date getLastDate() {
        return lastDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_regular.last_date
     *
     * @param lastDate the value for t_money_regular.last_date
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    public void setLastDate(Date lastDate) {
        this.lastDate = lastDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_regular.exe_time
     *
     * @return the value of t_money_regular.exe_time
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    public Integer getExeTime() {
        return exeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_regular.exe_time
     *
     * @param exeTime the value for t_money_regular.exe_time
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    public void setExeTime(Integer exeTime) {
        this.exeTime = exeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money_regular.remark
     *
     * @return the value of t_money_regular.remark
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money_regular.remark
     *
     * @param remark the value for t_money_regular.remark
     *
     * @mbggenerated Thu Sep 12 23:04:28 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}