CRATE DATABASE PERSONSPRING;

USE DATABASE PERSONSPRING;

CREATE TABLE USER (
	userID INT (20) NOT NULL AUTO_INCREMENT,
	userName VARCHAR (50) DEFAULT NULL ,
	password VARCHAR (50) DEFAULT NULL ,
	realName VARCHAR(50) DEFAULT null ,
	phoneNum VARCHAR(50) default null ,
	birthday DATETIME DEFAULT NULL ,
	registerDate DATETIME DEFAULT NULL ,
	level int default null,
	primary key(userID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 ;

insert into user(userName,password) values('lilei','111111');



CREATE TABLE T_LOGIN (
	LOGIN_ID INT (20) NOT NULL AUTO_INCREMENT,
	LOGIN_NAME VARCHAR (50) DEFAULT NULL UNIQUE COMMENT '注册登录名限制为EMAIL，唯一',
	LOGIN_PWD VARCHAR (50) DEFAULT NULL COMMENT '密码',
	LOGIN_LEVEL INT DEFAULT 0 COMMENT '0为游客，1为注册用户，2为管理员',
	LOGIN_IP VARCHAR(50) default null comment'IP',
	LOGIN_REGDATE DATETIME DEFAULT NULL COMMENT '注册日期',
	LOGIN_LastDate DATETIME DEFAULT NULL COMMENT '最近登录日期',
	PRIMARY KEY (LOGIN_ID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COMMENT '登录账户表';

CREATE TABLE T_USER (
	USER_ID INT (20) NOT NULL AUTO_INCREMENT,
	USER_LOGIN_ID INT (20) COMMENT '外键 LOGIN_ID',
	USER_FAMILY_ID INT (20) DEFAULT 0 COMMENT '家庭编号',
	USER_LEVEL int(20) DEFAULT 0 COMMENT '用户级别',
	USER_NAME VARCHAR (50) DEFAULT NULL COMMENT '用户姓名',
	USER_EMAIL VARCHAR (50) DEFAULT NULL COMMENT '用户EMAIL,同T_LOGIN.LOGIN_NAME',
	USER_PHONE VARCHAR (50) DEFAULT NULL COMMENT '用户电话',
	USER_BIRTHDAY datetime DEFAULT NULL COMMENT '用户生日',
	USER_REGDATE datetime DEFAULT NULL COMMENT '注册日期，同T_LOGIN.LOGIN_REGDATE_DATETIME',
	PRIMARY KEY (USER_ID),
	FOREIGN KEY (USER_LOGIN_ID) REFERENCES T_LOGIN (LOGIN_ID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COMMENT '用户表';

CREATE TABLE T_FAMILY (
	FAMILY_ID INT (20) NOT NULL AUTO_INCREMENT,
	FAMILY_NAME VARCHAR (50) DEFAULT NULL UNIQUE COMMENT '家庭账户名称',
	FAMILY_REGDATE DATETIME DEFAULT NULL COMMENT '家庭账户创建日期',
	PRIMARY KEY (FAMILY_ID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COMMENT '家庭账户表';


CREATE TABLE T_ACCOUNT (
	ACCT_ID INT (20) NOT NULL AUTO_INCREMENT,
	ACCT_USER_ID INT (20) DEFAULT NULL COMMENT '用户ID:T_USER.USER_ID',
	ACCT_NAME VARCHAR (50) DEFAULT NULL COMMENT '账户名称',
	ACCT_STATE VARCHAR (50) DEFAULT NULL COMMENT '账户状态：0未使用1在用',
	ACCT_CREATEDATE DATETIME DEFAULT NULL COMMENT '账户创建日期',
	PRIMARY KEY (ACCT_ID) ,
	FOREIGN KEY (ACCT_USER_ID) REFERENCES T_USER (USER_ID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COMMENT '账户表';

CREATE TABLE T_ACCOUNT_BOOK_TYPE (
	BOOK_ID INT (20) NOT NULL AUTO_INCREMENT,
	BOOK_TYPE VARCHAR (50) DEFAULT NULL COMMENT '账本类型 1.收支  2.借贷 3.投资 4.预算 5.其他',
	BOOK_TYPE_NAME VARCHAR (50) DEFAULT NULL COMMENT '账本类型对应的名称',
	BOOK_RATE FLOAT(6,2) DEFAULT NULL COMMENT '账本利率',
	BOOK_START_TIME DATETIME DEFAULT NULL COMMENT '账本类型开始时间',
	BOOK_END_TIME DATETIME DEFAULT NULL COMMENT '账本类型到期时间',
	PRIMARY KEY (BOOK_ID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COMMENT '账本类型表';

CREATE TABLE T_ASSET_DETAIL (
	ASSET_ID INT (20) NOT NULL AUTO_INCREMENT,
	ASSET_ACC_ID INT (20) DEFAULT NULL COMMENT '账户ID:T_ACCOUNT.ACC_ID',
	ASSET_USER_ID INT (20) DEFAULT NULL COMMENT '用户ID:T_USER.USER_ID',
	ASSET_STATE VARCHAR (50) DEFAULT NULL COMMENT '账本状态：0未使用1在用',
	ASSET_BOOK_TYPE VARCHAR (50) DEFAULT NULL COMMENT '账本类别:T_ACCOUNT_BOOK_TYPE.BOOK_TYPE',
	ASSET_Book_TYPE_NAME VARCHAR (50) DEFAULT NULL COMMENT '账本名称：T_ASSER_TYPE',
	ASSET_MONEY FLOAT(9,2) DEFAULT NULL COMMENT '金额 收入为+，支出为-',
	ASSET_RECORD_DATE DATETIME DEFAULT NULL COMMENT '记录日期  ',
	ASSET_RECORD_MONTH VARCHAR (50) DEFAULT NULL COMMENT '记录日期月份',
	ASSET_RECORD_YEAR VARCHAR (50) DEFAULT NULL COMMENT '记录日期年份 ',
	ASSET_STARTTIME DATETIME DEFAULT NULL COMMENT '计划开始时间',
	ASSET_ENDTIME DATETIME DEFAULT NULL COMMENT '计划到期时间',
	ASSET_REMARK VARCHAR (255) DEFAULT NULL COMMENT '描述 ',
	PRIMARY KEY (ASSET_ID) ,
	FOREIGN KEY (ASSET_ACC_ID) REFERENCES T_ACCOUNT (ACCT_ID),
	FOREIGN KEY (ASSET_USER_ID) REFERENCES T_USER (USER_ID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COMMENT '账户表';
